name: Build 和 Push Docker Image to GHCR

on:
  push:
    branches:
      - main # 或者你想要触发构建的分支
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 和 Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile  # 替换为你的 Dockerfile 路径，如果不在根目录
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
