name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 或者你想要触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 设置你的Docker Hub用户名，这里使用secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # 设置你的Docker Hub密码，这里使用secrets

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile # 指定 Dockerfile 文件路径
          push: true  # 如果需要推送到 Docker 仓库设置为 true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/xg-icons:latest # 设置你的镜像名称和tag，这里使用secrets，
            ${{ secrets.DOCKER_USERNAME }}/xg-icons:${{github.run_number}} #每次构建不同的tag
